# Generated by Django 4.0 on 2022-10-22 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vowel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vowel', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Katakana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('katakana', models.CharField(max_length=3)),
                ('vowel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.vowel')),
            ],
        ),
        migrations.CreateModel(
            name='Hiragana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiragana', models.CharField(max_length=3)),
                ('vowel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.vowel')),
            ],
        ),
    ]
