# Generated by Django 4.0 on 2022-10-24 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiragana',
            name='vowel',
        ),
        migrations.RemoveField(
            model_name='katakana',
            name='vowel',
        ),
        migrations.AddField(
            model_name='vowel',
            name='hiragana',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest_api.hiragana'),
        ),
        migrations.AddField(
            model_name='vowel',
            name='katakana',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='rest_api.katakana'),
        ),
    ]
