# Generated by Django 4.0 on 2022-10-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_remove_hiragana_vowel_remove_katakana_vowel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vowel',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='sounds/'),
        ),
    ]
