# Generated by Django 4.1.3 on 2022-11-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_example_hiragana_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='example',
            name='meaning',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
