# Generated by Django 4.1.3 on 2022-11-09 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_example_meaning'),
    ]

    operations = [
        migrations.AddField(
            model_name='katakana',
            name='ex',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='rest_api.example'),
        ),
    ]
