# Generated by Django 4.1.3 on 2022-11-09 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0006_katakana_ex'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiragana',
            name='kana_type',
            field=models.CharField(choices=[('gojuuon', 'gojuuon'), ('dakuon', 'dakuon'), ('handakuon', 'handakuon'), ('youon', 'youon'), ('sokuon', 'sokuons')], default=None, max_length=32, null=True),
        ),
    ]
