# Generated by Django 4.1.3 on 2022-11-11 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0009_alter_katakana_kana_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='katakana',
            name='kana_type',
        ),
    ]
