# Generated by Django 4.1.3 on 2022-12-28 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0012_kanatype_remove_hiragana_kana_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kanatype',
            name='hiragana',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.hiragana'),
        ),
        migrations.AddField(
            model_name='kanatype',
            name='katakana',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rest_api.katakana'),
        ),
    ]
