# Generated by Django 4.1.3 on 2022-12-28 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0013_kanatype_hiragana_kanatype_katakana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kanatype',
            name='hiragana',
        ),
        migrations.RemoveField(
            model_name='kanatype',
            name='katakana',
        ),
        migrations.AddField(
            model_name='kanatype',
            name='hiragana',
            field=models.ManyToManyField(default=None, null=True, to='rest_api.hiragana'),
        ),
        migrations.AddField(
            model_name='kanatype',
            name='katakana',
            field=models.ManyToManyField(default=None, null=True, to='rest_api.katakana'),
        ),
    ]
