# Generated by Django 4.1.3 on 2022-12-28 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0014_remove_kanatype_hiragana_remove_kanatype_katakana_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanatype',
            name='hiragana',
            field=models.ManyToManyField(default=None, to='rest_api.hiragana'),
        ),
        migrations.AlterField(
            model_name='kanatype',
            name='kana_type',
            field=models.CharField(choices=[('Gojuuon', 'Gojuuon'), ('Dakuon', 'Dakuon'), ('Handakuon', 'Handakuon'), ('Youon', 'Youon'), ('Sokuon', 'Sokuon')], default='Gojuuon', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='kanatype',
            name='katakana',
            field=models.ManyToManyField(default=None, to='rest_api.katakana'),
        ),
    ]
